# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

#config.vbguest.installer_options = { allow_kernel_upgrade: true }
if Vagrant.has_plugin? "vagrant-vbguest" 
config.vbguest.no_install = true 
config.vbguest.auto_update = false 
config.vbguest.no_remote = true
end

config.vm.define :servidorUbuntu do |servidorUbuntu|
  servidorUbuntu.vm.box ="bento/ubuntu-20.04"
  servidorUbuntu.vm.network :private_network, ip: "192.168.100.11"
  servidorUbuntu.vm.hostname = "servidorUbuntu"
  servidorUbuntu.vm.provision "shell", path: "provision.sh"
  servidorUbuntu.vm.provider "virtualbox" do |v|
   v.cpus = 2
   end
  end
end